apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - port: 10010
      targetPort: 10010
  selector:
    app: vp-traffic-monetisation-provider
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.180.0.0/16
  - 10.245.0.0/24
