apiVersion: v1
kind: ReplicationController
metadata:
  name: netisation-consumer-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netisation-consumer 
    spec:
      containers:
      - name: vp-traffic-monetisation-consumer
        image: hub.docker.vpclub.cn/vpclub_containers/vp-traffic-monetisation-consumer
        ports:
        - containerPort: 10020
#        - port: 10010
      imagePullSecrets:
      - name: aliregistrykey
####
apiVersion: v1
kind: Service
metadata:
  name: netisation-consumer-svc
  labels:
    app: netisation-consumer
spec:
  ports:
  - port: 80
    targetPort: 10020
    protocol: TCP
    name: http
  selector:
    app: netisation-consumer
