apiVersion: v1
kind: ReplicationController
metadata:
  name: traffic-consumertest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: traffic-contest
    spec:
      imagePullSecrets:
      - name: aliregistrykey
      containers:
      - name: vp-traffic-monetisation-consumertest
        image: hub.docker.vpclub.cn/vpclub_containers/vp-traffic-monetisation-consumertest:1.0.0
        env:
        - name: PROFILE
          value: 'test'
        ports:
        - containerPort: 10020
        volumeMounts:
        - mountPath: /app
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
  # directory location on host
          path: /tmp/vp-traffic-monetisation-consumer/app
