apiVersion: v1
kind: ReplicationController
metadata:
  name: traffic-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: traffic-con
    spec:
      containers:
      - name: vp-traffic-monetisation-consumer
        image: hub.docker.vpclub.cn/vpclub/java:8
        command: ["java","-Xmx128m","-Xss256k","-jar","/app/vp-traffic-monetisation-provider-1.0.0.jar","--spring.profiles.active=dev"]
        env:
        - name: PWD 
          value: /root/k8s-cluster/github/kubernetes/cluster/examples/vp-traffic-monetisation-consumer   
        ports:
        - containerPort: 10020
        volumeMounts:
        - mountPath: /app
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /root/k8s-cluster/github/kubernetes/cluster/examples/vp-traffic-monetisation-consumer/app 
      imagePullSecrets:
      - name: aliregistrykey

