apiVersion: v1
kind: ReplicationController
metadata:
  name: traffic-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: traffic-con
    spec:
      containers:
      - name: vp-traffic-monetisation-consumer
        image: hub.docker.vpclub.cn/vpclub_containers/vp-traffic-monetisation-consumer:1.0.0
        ports:
        - containerPort: 10020
#        - port: 10010
      imagePullSecrets:
      - name: aliregistrykey

